### ISSUE TITLE
Confirm Content from old Wiki is in new Pages - Attention: Need to delete unused field on dlrs__LookupRollupSummaryScheduleItems__c

### ISSUE THREAD

**Issue by mkolodner** [SFDO-Community-Sprints/DLRS-Documentation#10]
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/wiki/Attention:-Need-to-delete-unused-field-on-dlrs__LookupRollupSummaryScheduleItems__c

**Comment by mkolodner** [comment]
**Does not exist** on the Pages site.

**Comment by coriobriensfdo** [comment]
Transferred to FAQ page on new pages
