### ISSUE TITLE
Confirm Content from old Wiki is in new Pages - Code Contribution Guidelines

### ISSUE THREAD

**Issue by mkolodner** [SFDO-Community-Sprints/DLRS-Documentation#12]
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/wiki/Code-Contribution-Guidelines

NOTE: This page might be more appropriate to remain in package repo?

**Comment by sawlahasti** [comment]
Confirming that this content exists in the new documentation - https://sfdo-community-sprints.github.io/DLRS-Documentation/About%20Us%20&%20Contribution/contribution.html
