### ISSUE TITLE
Confirm Content from old Wiki is in new Pages - Contributing to DLRS

### ISSUE THREAD

**Issue by mkolodner** [SFDO-Community-Sprints/DLRS-Documentation#15]
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/wiki/Contributing-to-DLRS

**Comment by sawlahasti** [comment]
This page doesnt exist in the new site - should definitely be migrated

**Comment by coriobriensfdo** [comment]
It has already been migrated (on the "About Us & Contribution" page and code guidelines page, etc.
