### ISSUE TITLE
Confirm Content from old Wiki is in new Pages - Getting Started with DLRS (video)

### ISSUE THREAD

**Issue by mkolodner** [SFDO-Community-Sprints/DLRS-Documentation#20]
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/wiki/Getting-Started-with-DLRS-(video)

**Comment by sawlahasti** [comment]
This doesnt exist in new site. Recommendation to add the link in this section in new page - https://sfdo-community-sprints.github.io/DLRS-Documentation/#follow-the-dlrs-journey
