### ISSUE TITLE
Confirm Content from old Wiki is in new Pages - Temp old readme content to be audited for parity on docs pages site then deleted

### ISSUE THREAD

**Issue by mkolodner** [SFDO-Community-Sprints/DLRS-Documentation#23]
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/wiki/Temp---old-readme-content---to-be-audited-for-parity-on-docs-pages-site-then-deleted

**Comment by sawlahasti** [comment]
Some sections in the old Wiki pages are not in the new page

**Comment by coriobriensfdo** [comment]
Confirmed that all content is now in the pages site - will delete this temp wiki page. The content mentioned above is already in the new pages, just split into different sections such as on Getting Started, Implementation Considerations, Change Log, etc.
