### ISSUE TITLE
Confirm Content from old Wiki is in new Pages - Relationship Criteria (SOQL Queries)

### ISSUE THREAD

**Issue by mkolodner** [SFDO-Community-Sprints/DLRS-Documentation#25]
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/wiki/Relationship-Criteria-(SOQL-Queries)

**Comment by sawlahasti** [comment]
Confirming that all content from Old Wiki is in the new page - https://sfdo-community-sprints.github.io/DLRS-Documentation/Architecture/relationship-critera.html
