### ISSUE TITLE
Add Instructions on how to submit / inform team of bad documentation or links

### ISSUE THREAD

**Issue by sharicarlson13** [SFDO-Community-Sprints/DLRS-Documentation#35]
clear message to users - if you find old links let us know / log an issue

**Comment by coriobriensfdo** [comment]
Done! This is the message I used on a few of the wiki pages I suspected folks would land on from other sites. 

https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/wiki

# This Wiki page is no longer in use

## [Update as of Nov 23, 2022]

This wiki is being deprecated as all current information about DLRS can be found on our [website](https://sfdo-community-sprints.github.io/DLRS-Documentation/). Please check there for all information on DLRS including release notes, installation/uninstallation, the DLRS Cookbook, Issues & FAQ's, Architecture, about the Community team supporting the app, and how to contribute.

If you have landed on this page via another source (article link for example), please let us know and we will contact the author. Please contact us by either (in order of preference):

- [Log an issue](https://github.com/SFDO-Community-Sprints/DLRS-Documentation/issues) for the community team to action, including link to original source.
- [Trailblazer Community Post](https://trailhead.salesforce.com/trailblazer-community/groups/0F9300000009O5pCAE)
- Email sfdo-opensource@salesforce.com
