### ISSUE TITLE
Release 2.18 API Name (Lookup Summary Unique Name) enhancements #1236

### ISSUE THREAD

**Issue by sharicarlson13** [SFDO-Community-Sprints/DLRS-Documentation#49]
1. Review [Issue in Dev Repo](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/issues/1236)
2. Review [Documentation](https://sfdo-community-sprints.github.io/DLRS-Documentation/) to find any current references to this feature or screenshots that need to be updated. Create list of updates and locations in a comment on this Issue. 
3. Determine if issue needs a larger write up or explanation. If so, add [detailed documentation to this google doc](https://docs.google.com/document/d/1Rn8khqhhRv6ChBFLxgX6QGQoSU5-7qt7DLdUPQpHM-M/edit#heading=h.ubasbtaqe4yc) - ask in the Slack group if you are unsure. 
4. Move to In Review when you are done and at mention sharicarlson13 in a comment

**Comment by mkolodner** [comment]
I have added a comment on this item in the Dev Repo because these enhancements only apply to the new wizard. I have written the documentation to that effect. 
Moving to In Review and tagging @sharicarlson13
