### ISSUE TITLE
Review Cookbook versions

### ISSUE THREAD

**Issue by cpra12** [SFDO-Community-Sprints/DLRS-Documentation#7]
Check that the pages version of the Cookbook and the old wiki are the same, so that the old version can be deleted.

Then report back to Cori

Pages version is here: https://sfdo-community-sprints.github.io/DLRS-Documentation/Cookbook/

Original version from Sprints is here: https://github.com/SFDO-Community-Sprints/DLRS-Community-Sprints/wiki

Notes: need to check that the links still work / to other resources and in people's signatures.

**Comment by cpra12** [comment]
The two versions are compared - the only differences are in corrections to formatting, and the extra paragraph of introduction I wrote for the site.  

The original Sprint version is ready to be deleted.

**Comment by cpra12** [comment]
@coriobriensfdo assigned to you to delete the original Cookbook wiki.

**Comment by coriobriensfdo** [comment]
Done!
