### ISSUE TITLE
Confirm Content from old Wiki is in new Pages - Home

### ISSUE THREAD

**Issue by mkolodner** [SFDO-Community-Sprints/DLRS-Documentation#8]
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/wiki
Top level page of the old wiki has **several subsections**. Confirm that all the information in those sections already exists in the new pages site. If sections do not, either create Pages for them or create an issue for it to be done.

**Comment by sawlahasti** [comment]
Confirming that all content from Old Wiki is present in the new page - https://sfdo-community-sprints.github.io/DLRS-Documentation/Installation/

The only section in the old Wiki "Calculate Job Id" isn't present in the new page. However, the calculate Job Id doesn't have any content in old Wiki page as well. Do we want to have content in Calculate Job id section?

**Comment by coriobriensfdo** [comment]
Confirmed above comments and removed. If someone needs to write content for Calc Job ID we can add to new pages.
