### ISSUE TITLE
Confirm Content from old Wiki is in new Pages - Adding a new Field to the Rollup Definition

### ISSUE THREAD

**Issue by mkolodner** [SFDO-Community-Sprints/DLRS-Documentation#9]
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/wiki/Adding-a-new-Field-to-the-Rollup-Definition

Confirm that all the information on this page already exists in the new pages site. If not, either create a Page or comment on this issue that it needs doing.

**Comment by mkolodner** [comment]
I don't actually understand what this page is talking about and, therefore, don't think it needs to be transferred...
Confirm this and close @sharicarlson13 or @cpra12 ?

**Comment by sharicarlson13** [comment]
@mkolodner I don't think it needs to be transferred, but I don't think it should to be deleted in the development repo. It seems to be documentation for the developers who are working on the app.
